// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddS3DataSource(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddS3DataSource'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetGistConfig() {
  return window['go']['main']['App']['GetGistConfig']();
}

export function GetMounts() {
  return window['go']['main']['App']['GetMounts']();
}

export function GetS3DataSources() {
  return window['go']['main']['App']['GetS3DataSources']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsPasswordSet() {
  return window['go']['main']['App']['IsPasswordSet']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function Mount(arg1, arg2) {
  return window['go']['main']['App']['Mount'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetGistConfig(arg1, arg2) {
  return window['go']['main']['App']['SetGistConfig'](arg1, arg2);
}

export function SetMasterPassword(arg1) {
  return window['go']['main']['App']['SetMasterPassword'](arg1);
}

export function SyncToGist() {
  return window['go']['main']['App']['SyncToGist']();
}

export function TestS3Connection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestS3Connection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Unmount(arg1) {
  return window['go']['main']['App']['Unmount'](arg1);
}
