// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rclone} from '../models';
import {config} from '../models';

export function AddS3DataSource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function GetMounts():Promise<Array<rclone.MountInfo>>;

export function GetS3DataSources():Promise<Array<config.S3Config>>;

export function IsAutoStartEnabled():Promise<boolean>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<rclone.FileInfo>>;

export function Mount(arg1:string,arg2:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetGistConfig(arg1:string,arg2:string):Promise<void>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SyncToGist():Promise<void>;

export function TestS3Connection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function Unmount(arg1:string):Promise<void>;
